import { describe, it, expect, vi } from 'vitest'
import { generateEnvTemplate } from './environment'
import { prisma } from '@/lib/prisma'

vi.mock('@/lib/prisma', () => ({
  prisma: {
    environment: {
      findMany: vi.fn(),
    },
    envVariable: {
      findMany: vi.fn(),
    },
  },
}))

describe('generateEnvTemplate', () => {
  it('returns fallback message when no development environment exists', async () => {
    vi.mocked(prisma.environment.findMany).mockResolvedValueOnce([])
    vi.mocked(prisma.envVariable.findMany).mockResolvedValueOnce([])

    const result = await generateEnvTemplate('proj-1')
    expect(result).toBe('# No environments configured\n')
  })

  it('generates grouped .env template from development variables', async () => {
    vi.mocked(prisma.environment.findMany).mockResolvedValueOnce([
      { id: 'env-dev', name: 'development', type: 'development', url: null },
      { id: 'env-prod', name: 'production', type: 'production', url: null },
    ] as any)

    vi.mocked(prisma.envVariable.findMany).mockResolvedValueOnce([
      {
        id: 'var-1',
        environmentId: 'env-dev',
        key: 'DATABASE_URL',
        status: 'set',
        required: true,
        category: 'database',
        description: 'Postgres connection string',
      },
      {
        id: 'var-2',
        environmentId: 'env-dev',
        key: 'AUTH_SECRET',
        status: 'missing',
        required: false,
        category: 'auth',
        description: null,
      },
    ] as any)

    const result = await generateEnvTemplate('proj-1')
    expect(result).toContain('# Generated by Arbor')
    expect(result).toContain('# --- AUTH ---')
    expect(result).toContain('AUTH_SECRET= # optional')
    expect(result).toContain('# --- DATABASE ---')
    expect(result).toContain('DATABASE_URL= # Postgres connection string')
  })
})
